### ISSUE TITLE
PDF is corrupted

### ISSUE THREAD

**Issue by nmsmith** [DavidJaz/DynamicalSystemsBook#1]
I think the PDF you built today needs to be re-built. 😇

**Comment by jcberentsen** [comment]
I also have trouble opening the pdf. The prior commit works for me (https://github.com/DavidJaz/DynamicalSystemsBook/blob/e4ff0256532f75b82c4b6f35c1d1893a065511ed/book/DynamicalBook.pdf)

**Comment by DavidJaz** [comment]
Thanks ya'll! Sorry for the headache, it should be fixed now.
