### ISSUE TITLE
error in arity example?

### ISSUE THREAD

**Issue by bblfish** [DavidJaz/DynamicalSystemsBook#2]
I get the feeling the maps are wrong. Should it not be  1 ↦ 1, 2 ↦ 1, 3 ↦ 2 ?

![Screen Shot p.31](https://user-images.githubusercontent.com/124506/130353891-e47b3563-3a40-4635-9f9e-ec5113263279.png)

**Comment by DavidJaz** [comment]
Thanks! It's been fixed.
